"""add albums table

Revision ID: 6753befa1464
Revises: 9446af16ff9b
Create Date: 2025-09-07 06:35:08.432003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6753befa1464'
down_revision: Union[str, None] = '9446af16ff9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Creates the albums table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_title'), 'albums', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Removes the albums table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_albums_title'), table_name='albums')
    op.drop_table('albums')
    # ### end Alembic commands ###